### ISSUE TITLE
Seg fault from Rails logging

### ISSUE THREAD

**Issue by hwolff-mdsol** [JordiPolo/lorekeeper#5] opened 2017-06-30 15:52 UTC
Here's a one-line Rails command that gives me a segmentation fault, apparently inside lorekeeper.  More details on request!

$ rails c
...
Loading development environment (Rails 4.2.8)
2.4.0 :001 > **Rails.logger.error(NoMethodError.new)**
/Users/hwolff/.rvm/gems/ruby-2.4.0@plinth/gems/lorekeeper-1.6.1/lib/lorekeeper/json_logger.rb:118: [BUG] Segmentation fault at 0x00000000000000
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

-- Crash Report log information --------------------------------------------
...

**Comment by jcarres-mdsol** [comment] 2017-07-04 13:29
Woah, segfault, quite hardcore. 
I can reproduce it, we'll take a look

**Comment by ssteeg-mdsol** [comment] 2017-07-06 07:40
Issue seems to be in `oj`. The following reproduces the issue:
```rb
require 'oj'
Oj.dump(NoMethodError.new)
```

I've opened https://github.com/ohler55/oj/issues/404 asking for help. Will update this once I hear back from the Oj maintainers

**Comment by JordiPolo** [comment] 2017-07-12 04:51
Thanks @ssteeg-mdsol  for the work and @hwolff-mdsol  for the report, #6  solved this issue.
Please bundle update your app and enjoy. Closing this now.

**Closed by JordiPolo** 2017-07-12 04:51 UTC
